# Generated by Django 2.2.6 on 2023-01-27 17:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner', verbose_name='轮播图片')),
                ('index', models.IntegerField(default=0, verbose_name='轮播顺序')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '轮播课程',
                'verbose_name_plural': '轮播课程',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='序号')),
                ('name', models.CharField(max_length=100, verbose_name='章节名')),
            ],
            options={
                'verbose_name': '章节',
                'verbose_name_plural': '章节',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='课程名')),
                ('desc', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='课程概述')),
                ('target', models.TextField(blank=True, null=True, verbose_name='课程目标')),
                ('degree', models.CharField(choices=[('primary', '初级'), ('middle', '中级'), ('high', '高级')], max_length=10, verbose_name='难度')),
                ('learn_times', models.IntegerField(blank=True, default=0, null=True, verbose_name='学习时长(分钟数)')),
                ('stu_num', models.IntegerField(blank=True, default=0, null=True, verbose_name='学习人数')),
                ('fav_nums', models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏人数')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/images/', verbose_name='封面图')),
                ('click_nums', models.IntegerField(blank=True, default=0, null=True, verbose_name='点击数')),
                ('tag', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='课程标签')),
                ('readme', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='课程须知')),
                ('teacher_tell', models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='老师告诉你')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程',
                'verbose_name_plural': '课程',
            },
        ),
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='类别名', max_length=30, verbose_name='类别名')),
                ('code', models.CharField(default='', help_text='类别code', max_length=30, verbose_name='类别code')),
                ('desc', models.TextField(default='', help_text='类别描述', verbose_name='类别描述')),
                ('category_type', models.IntegerField(choices=[(1, '一级类目'), (2, '二级类目')], help_text='类目级别', verbose_name='类目级别')),
                ('is_tab', models.BooleanField(default=False, help_text='是否导航', verbose_name='是否导航')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '课程类别',
                'verbose_name_plural': '课程类别',
            },
        ),
        migrations.CreateModel(
            name='Courseware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='序号')),
                ('file_type', models.CharField(choices=[('video', '视频(mp4)'), ('ppt', '课件(pdf)'), ('document', '文档(dox,pdf,txt)')], max_length=10, verbose_name='文件类型')),
                ('url', models.FileField(max_length=200, upload_to='courses/files/%Y/%m', verbose_name='上传课件')),
                ('name', models.CharField(max_length=100, verbose_name='课件名')),
            ],
            options={
                'verbose_name': '课件',
                'verbose_name_plural': '课件',
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(verbose_name='序号')),
                ('name', models.CharField(max_length=100, verbose_name='课时名')),
            ],
            options={
                'verbose_name': '课时',
                'verbose_name_plural': '课时',
            },
        ),
        migrations.CreateModel(
            name='UserLearningCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('isDelete', models.BooleanField(default=False)),
                ('course', models.ForeignKey(help_text='课程id', on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
            ],
            options={
                'verbose_name': '在学课程',
                'verbose_name_plural': '在学课程',
            },
        ),
    ]
