# Generated by Django 2.2.6 on 2023-02-17 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20230127_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseware',
            name='file_type',
            field=models.CharField(choices=[('video', '视频(mp4)'), ('ppt', 'PPT(ppt、pptx)'), ('document', '其他文档(pdf、doc、docx、xlsx、xls、jpg、png)')], max_length=10, verbose_name='文件类型'),
        ),
    ]
