# Generated by Django 2.2.6 on 2023-02-19 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_auto_20230217_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='队号')),
                ('name', models.CharField(help_text='队伍唯一标识', max_length=100, unique=True, verbose_name='队名')),
                ('introduction', models.TextField(max_length=500, verbose_name='团队简介')),
                ('member', models.ManyToManyField(related_name='teams', related_query_name='team', to=settings.AUTH_USER_MODEL, verbose_name='队员')),
            ],
            options={
                'verbose_name': '学习团队',
                'verbose_name_plural': '学习团队',
            },
        ),
        migrations.CreateModel(
            name='CourseGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='组号')),
                ('name', models.CharField(help_text='小组唯一标识', max_length=100, unique=True, verbose_name='组名')),
                ('course', models.ForeignKey(help_text='课程', on_delete=django.db.models.deletion.CASCADE, to='courses.Course', verbose_name='课程')),
                ('member', models.ManyToManyField(related_name='course_groups', related_query_name='course_group', to=settings.AUTH_USER_MODEL, verbose_name='组员')),
            ],
            options={
                'verbose_name': '学习小组',
                'verbose_name_plural': '学习小组',
            },
        ),
    ]
