# Generated by Django 2.2.6 on 2023-02-19 19:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_coursegroup_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlearningcourse',
            options={'verbose_name': '选课表', 'verbose_name_plural': '选课表'},
        ),
        migrations.AlterField(
            model_name='userlearningcourse',
            name='course',
            field=models.ForeignKey(help_text='课程id', on_delete=django.db.models.deletion.CASCADE, related_query_name='learn_students', to='courses.Course', verbose_name='课程'),
        ),
        migrations.AlterField(
            model_name='userlearningcourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_query_name='learn_courses', to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
