# Generated by Django 2.2.6 on 2023-02-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20230219_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='name',
            field=models.CharField(max_length=100, verbose_name='组名'),
        ),
    ]
