# Generated by Django 2.2.6 on 2024-02-19 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_coursegroup_maxnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_hide',
            field=models.BooleanField(default=False, verbose_name='是否隐藏'),
            preserve_default=False,
        ),
    ]
