# Generated by Django 2.2.6 on 2023-02-22 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_coursegroup_maxnum'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelOneReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('public_date_time', models.DateTimeField(verbose_name='发布日期时间')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='level_one_reply', to=settings.AUTH_USER_MODEL, verbose_name='回复者')),
            ],
            options={
                'verbose_name': '一级回帖',
                'verbose_name_plural': '一级回帖',
                'ordering': ['public_date_time'],
            },
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('public_date_time', models.DateTimeField(verbose_name='发布日期时间')),
                ('course', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to='courses.Course', verbose_name='归属课程')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='topic', to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': '话题',
                'verbose_name_plural': '话题',
                'ordering': ['public_date_time'],
            },
        ),
        migrations.CreateModel(
            name='TopicPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_name', models.CharField(max_length=20, verbose_name='插图名字')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='comments/pictures/', verbose_name='插图')),
                ('topic', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='topic_picture', to='comments.Topics', verbose_name='归属话题')),
            ],
            options={
                'verbose_name': '话题插图',
                'verbose_name_plural': '话题插图',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='LevelTwoReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='内容')),
                ('public_date_time', models.DateTimeField(verbose_name='发布日期时间')),
                ('level_one_reply', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='level_one_reply', to='comments.LevelOneReply', verbose_name='一级回帖')),
                ('owner', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='level_two_reply', to=settings.AUTH_USER_MODEL, verbose_name='回复者')),
            ],
            options={
                'verbose_name': '二级回帖',
                'verbose_name_plural': '二级回帖',
                'ordering': ['public_date_time'],
            },
        ),
        migrations.AddField(
            model_name='levelonereply',
            name='topic',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='level_one_reply', to='comments.Topics', verbose_name='话题'),
        ),
    ]
