# Generated by Django 2.2.6 on 2023-01-27 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='image',
            field=models.ImageField(blank=True, upload_to='users/images/organization/', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='users/image/userprofile/default.png', max_length=200, upload_to='users/image/userprofile/', verbose_name='头像'),
        ),
    ]
