# Generated by Django 2.2.6 on 2023-01-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230127_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='self_introduction',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='自我介绍'),
        ),
    ]
