# Generated by Django 2.2.6 on 2023-01-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20230128_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='self_introduction',
            field=models.TextField(blank=True, default='', null=True, verbose_name='自我介绍'),
        ),
    ]
