# Generated by Django 2.2.6 on 2023-01-27 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='考试名称')),
                ('tips', models.TextField(default='暂无', verbose_name='考生须知')),
                ('top_score', models.PositiveSmallIntegerField(default=100, verbose_name='总分')),
                ('exam_date', models.DateTimeField(verbose_name='考试日期时间')),
                ('total_time', models.PositiveSmallIntegerField(default=120, help_text='时长按照分钟填写', verbose_name='考试时长')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_answer', models.TextField(blank=True, null=True, verbose_name='学生的作答')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='得分')),
            ],
            options={
                'verbose_name': '答题记录（考试）',
                'verbose_name_plural': '答题记录（考试）',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ExamAnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(blank=True, max_length=20, verbose_name='归属老师')),
            ],
            options={
                'verbose_name': '考试答卷',
                'verbose_name_plural': '考试答卷',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='题目')),
                ('right_answer', models.TextField(verbose_name='参考答案')),
                ('analysis', models.TextField(default='暂无', verbose_name='解析')),
                ('question_type', models.CharField(choices=[('1', '单选题'), ('2', '多选题'), ('3', '判断题'), ('4', '填空题'), ('5', '简答题'), ('6', '问答题'), ('7', '编程题'), ('8', '其他客观题'), ('9', '其他主观题')], max_length=1, verbose_name='题型')),
                ('level', models.CharField(choices=[('1', '入门'), ('2', '简单'), ('3', '普通'), ('4', '较难'), ('5', '困难')], default='1', max_length=1, verbose_name='难度等级')),
                ('score', models.PositiveSmallIntegerField(verbose_name='分值')),
                ('auto_judge', models.BooleanField(verbose_name='是否机评')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='作业名称')),
                ('tips', models.TextField(default='暂无', verbose_name='作业说明')),
                ('public_date', models.DateTimeField(verbose_name='发布日期时间')),
                ('top_score', models.PositiveSmallIntegerField(default=100, verbose_name='总分')),
            ],
            options={
                'verbose_name': '作业',
                'verbose_name_plural': '作业',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswerRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_answer', models.TextField(blank=True, null=True, verbose_name='学生的作答')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='得分')),
            ],
            options={
                'verbose_name': '答题记录（作业）',
                'verbose_name_plural': '答题记录（作业）',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='QuizAnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(blank=True, max_length=20, verbose_name='归属老师')),
                ('quiz', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answer_sheet', to='QuizAndExam.Quiz', verbose_name='作业')),
            ],
            options={
                'verbose_name': '作业答卷',
                'verbose_name_plural': '作业答卷',
                'ordering': ['id'],
            },
        ),
    ]
