# Generated by Django 2.2.6 on 2023-01-27 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('QuizAndExam', '0001_initial'),
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswersheet',
            name='student',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answer_sheet', to=settings.AUTH_USER_MODEL, verbose_name='答题学生'),
        ),
        migrations.AddField(
            model_name='quizanswerrecord',
            name='question',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answer_record', to='QuizAndExam.Questions', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='quizanswerrecord',
            name='quiz_answer_sheet',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answer_record', to='QuizAndExam.QuizAnswerSheet', verbose_name='作业答卷'),
        ),
        migrations.AddField(
            model_name='quizanswerrecord',
            name='student',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answer_record', to=settings.AUTH_USER_MODEL, verbose_name='答题学生'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='courses.Lesson', verbose_name='课时'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='quizs', related_query_name='quiz', to='QuizAndExam.Questions', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='teacher',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='quizs', to=settings.AUTH_USER_MODEL, verbose_name='老师'),
        ),
        migrations.AddField(
            model_name='questions',
            name='teacher',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='老师'),
        ),
        migrations.AddField(
            model_name='examanswersheet',
            name='exam',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='exam_answer_sheet', to='QuizAndExam.Exam', verbose_name='考试'),
        ),
        migrations.AddField(
            model_name='examanswersheet',
            name='student',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='exam_answer_sheet', to=settings.AUTH_USER_MODEL, verbose_name='答题学生'),
        ),
        migrations.AddField(
            model_name='examanswerrecord',
            name='exam_answer_sheet',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='exam_answer_record', to='QuizAndExam.ExamAnswerSheet', verbose_name='考试答卷'),
        ),
        migrations.AddField(
            model_name='examanswerrecord',
            name='question',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='exam_answer_record', to='QuizAndExam.Questions', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='examanswerrecord',
            name='student',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='exam_answer_record', to=settings.AUTH_USER_MODEL, verbose_name='答题学生'),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='exam', to='courses.Course', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='exam',
            name='questions',
            field=models.ManyToManyField(blank=True, related_name='exams', related_query_name='exam', to='QuizAndExam.Questions', verbose_name='题目'),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to=settings.AUTH_USER_MODEL, verbose_name='老师'),
        ),
    ]
