# Generated by Django 2.2.6 on 2023-01-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizAndExam', '0002_auto_20230127_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='show_result',
            field=models.BooleanField(default=False, verbose_name='公示评分结果'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='show_result',
            field=models.BooleanField(default=False, verbose_name='公示评分结果'),
        ),
    ]
