# Generated by Django 2.2.6 on 2023-02-01 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizAndExam', '0003_auto_20230130_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswersheet',
            name='all_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='总分'),
        ),
        migrations.AddField(
            model_name='quizanswersheet',
            name='all_score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='总分'),
        ),
    ]
