# Generated by Django 2.2.6 on 2023-02-02 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizAndExam', '0004_auto_20230201_1500'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_name', models.CharField(max_length=20, verbose_name='插图名字')),
                ('image', models.ImageField(blank=True, max_length=200, null=True, upload_to='question/picture/', verbose_name='插图')),
                ('question', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='question_picture', to='QuizAndExam.Questions', verbose_name='题目')),
            ],
            options={
                'verbose_name': '题目插图',
                'verbose_name_plural': '题目插图',
                'ordering': ['id'],
            },
        ),
    ]
