# Generated by Django 2.2.6 on 2023-02-02 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizAndExam', '0005_questionspicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionspicture',
            old_name='image',
            new_name='picture',
        ),
    ]
